// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class AddReviewBodyParam extends Equatable {
  final int activityId;
  final String description;
  final int stars;
  final int userId;

  @override
  List<Object> get props => <Object>[
    activityId,
    description,
    stars,
    userId,
  ];

  const AddReviewBodyParam({
    required this.activityId,
    required this.description,
    required this.stars,
    required this.userId,
  });

  Json toMap() {
    return <String, dynamic>{
      'activity_id': activityId,
      'description': description,
      'stars': stars,
      'user_id': userId,
    };
  }

  AddReviewBodyParam copyWith({
    int? activityId,
    String? description,
    int? stars,
    int? userId,
  }) {
    return AddReviewBodyParam(
      activityId: activityId ?? this.activityId,
      description: description ?? this.description,
      stars: stars ?? this.stars,
      userId: userId ?? this.userId,
    );
  }
}
