// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class EditReviewBodyParam extends Equatable {
  final String description;
  final int stars;

  @override
  List<Object> get props => <Object>[
    description,
    stars,
  ];

  const EditReviewBodyParam({
    required this.description,
    required this.stars,
  });

  Json toMap() {
    return <String, dynamic>{
      'description': description,
      'stars': stars,
    };
  }

  EditReviewBodyParam copyWith({
    String? description,
    int? stars,
  }) {
    return EditReviewBodyParam(
      description: description ?? this.description,
      stars: stars ?? this.stars,
    );
  }
}
