// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class FindReviewUrlParam extends Equatable {
  final int reviewId;

  @override
  List<Object> get props => <Object>[
    reviewId,
  ];

  const FindReviewUrlParam({
    required this.reviewId,
  });

  Json toMap() {
    return <String, dynamic>{
      'review_id': reviewId,
    };
  }

  FindReviewUrlParam copyWith({
    int? reviewId,
  }) {
    return FindReviewUrlParam(
      reviewId: reviewId ?? this.reviewId,
    );
  }
}
