// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';

class IndexReviewsParam extends Equatable {
  final int activityId;

  @override
  List<Object> get props => <Object>[
    activityId,
  ];

  const IndexReviewsParam({
    required this.activityId,
  });

  Json toMap() {
    return <String, dynamic>{
      'activity_id': activityId,
    };
  }

  IndexReviewsParam copyWith({
    int? activityId,
  }) {
    return IndexReviewsParam(
      activityId: activityId ?? this.activityId,
    );
  }
}
