// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class ListReviewsQueryParam extends Equatable {
  final int? page;
  final int? perPage;
  final int? activityId;
  final bool? wasApproved;
  final bool? isVerified;

  @override
  List<Object> get props => <Object>[
    page ?? 0,
    perPage ?? 0,
    activityId ?? 0,
    wasApproved ?? false,
    isVerified ?? false,
  ];

  const ListReviewsQueryParam({
    this.page,
    this.perPage,
    this.activityId,
    this.wasApproved,
    this.isVerified,
  });

  Json toMap() {
    return <String, dynamic>{
      'page': page,
      'per_page': perPage,
      'activity_id': activityId,
      'was_approved': wasApproved,
      'is_verified': isVerified,
    };
  }

  ListReviewsQueryParam copyWith({
    int? page,
    int? perPage,
    int? activityId,
    bool? wasApproved,
    bool? isVerified,
  }) {
    return ListReviewsQueryParam(
      page: page ?? this.page,
      perPage: perPage ?? this.perPage,
      activityId: activityId ?? this.activityId,
      wasApproved: wasApproved ?? this.wasApproved,
      isVerified: isVerified ?? this.isVerified,
    );
  }
}
