// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class UpdateReviewBodyParam extends Equatable {
  final bool isVerified;
  final bool wasApproved;

  @override
  List<Object> get props => <Object>[
    isVerified,
    wasApproved,
  ];

  const UpdateReviewBodyParam({
    required this.isVerified,
    required this.wasApproved,
  });

  Json toMap() {
    return <String, dynamic>{
      'is_verified': isVerified,
      'was_approved': wasApproved,
    };
  }

  UpdateReviewBodyParam copyWith({
    bool? isVerified,
    bool? wasApproved,
  }) {
    return UpdateReviewBodyParam(
      isVerified: isVerified ?? this.isVerified,
      wasApproved: wasApproved ?? this.wasApproved,
    );
  }
}
