name: 'Changeset Release'
description: 'Open PRs and create tags for releases using changesets'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  NPM_TOKEN:
    description: 'NPM token'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install Node.js dependencies
      shell: bash
      run: npm install

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git config --global push.autoSetupRemote true

    - name: Create release or open pull request release
      uses: changesets/action@v1
      with:
        title: 'chore: update versions'
        commit: 'chore: update versions'
        publish: npx changeset publish
        createGithubReleases: true
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
