// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class EditEventBodyParam extends Equatable {
  final String name;
  final String description;
  final String descriptionHtml;
  final String type;
  final String startAt;
  final String endsAt;
  final int addressId;
  final String addressState;
  final String addressCity;
  final String addressNeighborhood;
  final String addressAddress;
  final String? addressZipCode;
  final String? addressNumber;
  final String? addressComplement;

  @override
  List<Object> get props => <Object>[
    name,
    description,
    descriptionHtml,
    type,
    startAt,
    endsAt,
    addressId,
    addressState,
    addressCity,
    addressNeighborhood,
    addressAddress,
    addressZipCode ?? '',
    addressNumber ?? '',
    addressComplement ?? '',
  ];

  const EditEventBodyParam({
    required this.name,
    required this.description,
    required this.descriptionHtml,
    required this.type,
    required this.startAt,
    required this.endsAt,
    required this.addressId,
    required this.addressState,
    required this.addressCity,
    required this.addressNeighborhood,
    required this.addressAddress,
    this.addressZipCode,
    this.addressNumber,
    this.addressComplement,
  });

  Json toMap() {
    return <String, dynamic>{
      'name': name,
      'description': description,
      'description_html': descriptionHtml,
      'type': type,
      'start_at': startAt,
      'ends_at': endsAt,
      'address': {
        'id': addressId,
        'state': addressState,
        'city': addressCity,
        'neighborhood': addressNeighborhood,
        'address': addressAddress,
        'zip_code': addressZipCode,
        'number': addressNumber,
        'complement': addressComplement,
      },
    };
  }

  EditEventBodyParam copyWith({
    String? name,
    String? description,
    String? descriptionHtml,
    String? type,
    String? startAt,
    String? endsAt,
    int? addressId,
    String? addressState,
    String? addressCity,
    String? addressNeighborhood,
    String? addressAddress,
    String? addressZipCode,
    String? addressNumber,
    String? addressComplement,
  }) {
    return EditEventBodyParam(
      name: name ?? this.name,
      description: description ?? this.description,
      descriptionHtml: descriptionHtml ?? this.descriptionHtml,
      type: type ?? this.type,
      startAt: startAt ?? this.startAt,
      endsAt: endsAt ?? this.endsAt,
      addressId: addressId ?? this.addressId,
      addressState: addressState ?? this.addressState,
      addressCity: addressCity ?? this.addressCity,
      addressNeighborhood: addressNeighborhood ?? this.addressNeighborhood,
      addressAddress: addressAddress ?? this.addressAddress,
      addressZipCode: addressZipCode ?? this.addressZipCode,
      addressNumber: addressNumber ?? this.addressNumber,
      addressComplement: addressComplement ?? this.addressComplement,
    );
  }
}
