// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class EditEventUrlParam extends Equatable {
  final int eventId;

  @override
  List<Object> get props => <Object>[
    eventId,
  ];

  const EditEventUrlParam({
    required this.eventId,
  });

  Json toMap() {
    return <String, dynamic>{
      'event_id': eventId,
    };
  }

  EditEventUrlParam copyWith({
    int? eventId,
  }) {
    return EditEventUrlParam(
      eventId: eventId ?? this.eventId,
    );
  }
}
