// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class ListEventsQueryParam extends Equatable {
  final int? page;
  final int? perPage;
  final String? name;
  final String? type;
  final String? city;

  @override
  List<Object> get props => <Object>[
    page ?? 0,
    perPage ?? 0,
    name ?? '',
    type ?? '',
    city ?? '',
  ];

  const ListEventsQueryParam({
    this.page,
    this.perPage,
    this.name,
    this.type,
    this.city,
  });

  Json toMap() {
    return <String, dynamic>{
      'page': page,
      'per_page': perPage,
      'name': name,
      'type': type,
      'city': city,
    };
  }

  ListEventsQueryParam copyWith({
    int? page,
    int? perPage,
    String? name,
    String? type,
    String? city,
  }) {
    return ListEventsQueryParam(
      page: page ?? this.page,
      perPage: perPage ?? this.perPage,
      name: name ?? this.name,
      type: type ?? this.type,
      city: city ?? this.city,
    );
  }
}
