// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class RemoveEventUrlParam extends Equatable {
  final int eventId;

  @override
  List<Object> get props => <Object>[
    eventId,
  ];

  const RemoveEventUrlParam({
    required this.eventId,
  });

  Json toMap() {
    return <String, dynamic>{
      'event_id': eventId,
    };
  }

  RemoveEventUrlParam copyWith({
    int? eventId,
  }) {
    return RemoveEventUrlParam(
      eventId: eventId ?? this.eventId,
    );
  }
}
