version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "guiar.me"
  - package-ecosystem: "pub"
    directory: "/packages/sdks/flutter"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "sdk-flutter"
  - package-ecosystem: "pub"
    directory: "/packages/ui/flutter"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ui-flutter"
