name: 'Send Slack Message'
description: 'Send message to Slack via Incoming Webhook'
runs:
  using: 'composite'
  steps:
    - name: Check commit message
      id: check
      run: |
        reg="^chore: update versions"

        if [[ "${{ github.event.workflow_run.head_commit.message }}" =~ $reg ]]; then
            echo "is_version_update=true" >> $GITHUB_OUTPUT
        else
            echo "is_version_update=false" >> $GITHUB_OUTPUT
        fi

    - name: Notify Slack
      if: steps.check.outputs.is_version_update == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          const response = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          const webhookUrl = '${{ secrets.SLACK_WEBHOOK_URL }}';
          const tag = response.data.tag_name;
          const body = response.data.body || '*No documented changes*';
          const text = `🚀 New Release - ${tag}

          ### Links
          - [${tag}](https://github.com/guiar-me/api/releases/tag/${tag})

          ${body}`;

          await fetch(webhookUrl, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json'
            },
            body: JSON.stringify({ text })
          });
