// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';
import 'package:sdk_flutter/domain/models/address_model.dart';
import 'package:sdk_flutter/domain/models/image_model.dart';

class ActivityModel extends Equatable {
  final int id;
  final String name;
  final String description;
  final String category;
  final bool isVerified;
  final bool isFavorite;
  final int? price;
  final String? pricePrefix;
  final String? priceSuffix;
  final double stars;
  final int totalReviews;
  final List<AddressModel> addresses;
  final List<ImageModel> images;
  final String createdAt;
  final String updatedAt;

  @override
  List<Object> get props => <Object>[
    id,
    name,
    description,
    category,
    isVerified,
    isFavorite,
    price ?? 0,
    pricePrefix ?? '',
    priceSuffix ?? '',
    stars,
    totalReviews,
    addresses,
    images,
    createdAt,
    updatedAt,
  ];

  const ActivityModel({
    required this.id,
    required this.name,
    required this.description,
    required this.category,
    required this.isVerified,
    required this.isFavorite,
    this.price,
    this.pricePrefix,
    this.priceSuffix,
    required this.stars,
    required this.totalReviews,
    required this.addresses,
    required this.images,
    required this.createdAt,
    required this.updatedAt,
  });

  static ActivityModel fromMap(Json data) {
    return ActivityModel(
      id: data['id'],
      name: data['name'],
      description: data['description'],
      category: data['category'],
      isVerified: data['is_verified'],
      isFavorite: data['is_favorite'],
      price: data['price'],
      pricePrefix: data['price_prefix'],
      priceSuffix: data['price_suffix'],
      stars: data['stars'] is int ? data['stars'].toDouble() : data['stars'],
      totalReviews: data['total_reviews'],
      addresses: AddressModel.fromList(data['addresses'] ?? []),
      images: ImageModel.fromList(data['images'] ?? []),
      createdAt: data['created_at'],
      updatedAt: data['updated_at'],
    );
  }

  static List<ActivityModel> fromList(List<dynamic> list) {
    return list.map((dynamic item) => ActivityModel.fromMap(item)).toList();
  }
}
