// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class AddressModel extends Equatable {
  final int id;
  final int? addressableId;
  final String? addressableType;
  final String state;
  final String city;
  final String neighborhood;
  final String address;
  final String? zipCode;
  final String? number;
  final String? complement;
  final String createdAt;
  final String updatedAt;

  @override
  List<Object> get props => <Object>[
    id,
    addressableId ?? 0,
    addressableType ?? '',
    state,
    city,
    neighborhood,
    address,
    zipCode ?? '',
    number ?? '',
    complement ?? '',
    createdAt,
    updatedAt,
  ];

  const AddressModel({
    required this.id,
    this.addressableId,
    this.addressableType,
    required this.state,
    required this.city,
    required this.neighborhood,
    required this.address,
    this.zipCode,
    this.number,
    this.complement,
    required this.createdAt,
    required this.updatedAt,
  });

  static AddressModel fromMap(Json data) {
    return AddressModel(
      id: data['id'],
      addressableId: data['addressable_id'],
      addressableType: data['addressable_type'],
      state: data['state'],
      city: data['city'],
      neighborhood: data['neighborhood'],
      address: data['address'],
      zipCode: data['zip_code'],
      number: data['number'],
      complement: data['complement'],
      createdAt: data['created_at'],
      updatedAt: data['updated_at'],
    );
  }

  static List<AddressModel> fromList(List<dynamic> list) {
    return list.map((dynamic item) => AddressModel.fromMap(item)).toList();
  }
}
