// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';


class AddressModel extends Equatable {
  final int? id;
  final int? activityId;
  final String? state;
  final String? city;
  final String? neighborhood;
  final String? address;
  final String? zipCode;
  final String? number;
  final String? complement;
  final String? createdAt;
  final String? updatedAt;

  @override
  List<Object> get props => <Object>[
    id ?? 0,
    activityId ?? 0,
    state ?? '',
    city ?? '',
    neighborhood ?? '',
    address ?? '',
    zipCode ?? '',
    number ?? '',
    complement ?? '',
    createdAt ?? '',
    updatedAt ?? '',
  ];

  const AddressModel({
    this.id,
    this.activityId,
    this.state,
    this.city,
    this.neighborhood,
    this.address,
    this.zipCode,
    this.number,
    this.complement,
    this.createdAt,
    this.updatedAt,
  });

  static AddressModel fromMap(Json data) {
    return AddressModel(
      id: data['id'],
      activityId: data['activity_id'],
      state: data['state'],
      city: data['city'],
      neighborhood: data['neighborhood'],
      address: data['address'],
      zipCode: data['zip_code'],
      number: data['number'],
      complement: data['complement'],
      createdAt: data['created_at'],
      updatedAt: data['updated_at'],
    );
  }
}
