// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';


class CityModel extends Equatable {
  final String name;
  final String nameHumanReadable;
  final String imageUrl;

  @override
  List<Object> get props => <Object>[
    name,
    nameHumanReadable,
    imageUrl,
  ];

  const CityModel({
    required this.name,
    required this.nameHumanReadable,
    required this.imageUrl,
  });

  static CityModel fromMap(Json data) {
    return CityModel(
      name: data['name'],
      nameHumanReadable: data['name_human_readable'],
      imageUrl: data['image_url'],
    );
  }

  static List<CityModel> fromList(List<dynamic> list) {
    return list.map((dynamic item) => CityModel.fromMap(item)).toList();
  }
}
