// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class CouponModel extends Equatable {
  final int id;
  final String code;
  final String type;
  final double value;
  final bool isUsed;
  final int activityId;
  final int subscriptionId;
  final String createdAt;
  final String updatedAt;

  @override
  List<Object> get props => <Object>[
    id,
    code,
    type,
    value,
    isUsed,
    activityId,
    subscriptionId,
    createdAt,
    updatedAt,
  ];

  const CouponModel({
    required this.id,
    required this.code,
    required this.type,
    required this.value,
    required this.isUsed,
    required this.activityId,
    required this.subscriptionId,
    required this.createdAt,
    required this.updatedAt,
  });

  static CouponModel fromMap(Json data) {
    return CouponModel(
      id: data['id'],
      code: data['code'],
      type: data['type'],
      value: data['value'] is int ? data['value'].toDouble() : data['value'],
      isUsed: data['is_used'],
      activityId: data['activity_id'],
      subscriptionId: data['subscription_id'],
      createdAt: data['created_at'],
      updatedAt: data['updated_at'],
    );
  }

  static List<CouponModel> fromList(List<dynamic> list) {
    return list.map((dynamic item) => CouponModel.fromMap(item)).toList();
  }
}
