// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';
import 'package:sdk_flutter/domain/models/user_model.dart';

class CreditCardModel extends Equatable {
  final int id;
  final String holderCpf;
  final String paymentToken;
  final String cardMask;
  final UserModel user;
  final String createdAt;
  final String updatedAt;

  @override
  List<Object> get props => <Object>[
    id,
    holderCpf,
    paymentToken,
    cardMask,
    user,
    createdAt,
    updatedAt,
  ];

  const CreditCardModel({
    required this.id,
    required this.holderCpf,
    required this.paymentToken,
    required this.cardMask,
    required this.user,
    required this.createdAt,
    required this.updatedAt,
  });

  static CreditCardModel fromMap(Json data) {
    return CreditCardModel(
      id: data['id'],
      holderCpf: data['holder_cpf'],
      paymentToken: data['payment_token'],
      cardMask: data['card_mask'],
      user: UserModel.fromMap(data['user']),
      createdAt: data['created_at'],
      updatedAt: data['updated_at'],
    );
  }

  static List<CreditCardModel> fromList(List<dynamic> list) {
    return list.map((dynamic item) => CreditCardModel.fromMap(item)).toList();
  }
}
