// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class EventModel extends Equatable {
  final int id;
  final String name;
  final String description;
  final String descriptionHtml;
  final String type;
  final String startAt;
  final String endsAt;
  final List<AddressModel> addresses;
  final String createdAt;
  final String updatedAt;

  @override
  List<Object> get props => <Object>[
    id,
    name,
    description,
    descriptionHtml,
    type,
    startAt,
    endsAt,
    addresses,
    createdAt,
    updatedAt,
  ];

  const EventModel({
    required this.id,
    required this.name,
    required this.description,
    required this.descriptionHtml,
    required this.type,
    required this.startAt,
    required this.endsAt,
    required this.addresses,
    required this.createdAt,
    required this.updatedAt,
  });

  static EventModel fromMap(Json data) {
    return EventModel(
      id: data['id'],
      name: data['name'],
      description: data['description'],
      descriptionHtml: data['description_html'],
      type: data['type'],
      startAt: data['start_at'],
      endsAt: data['ends_at'],
      addresses: AddressModel.fromList(data['addresses'] ?? []),
      createdAt: data['created_at'],
      updatedAt: data['updated_at'],
    );
  }

  static List<EventModel> fromList(List<dynamic> list) {
    return list.map((dynamic item) => EventModel.fromMap(item)).toList();
  }
}
