// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';
import 'package:sdk_flutter/domain/models/activity_model.dart';

class FavoriteModel extends Equatable {
  final int id;
  final ActivityModel activity;
  final String createdAt;
  final String updatedAt;

  @override
  List<Object> get props => <Object>[
    id,
    activity,
    createdAt,
    updatedAt,
  ];

  const FavoriteModel({
    required this.id,
    required this.activity,
    required this.createdAt,
    required this.updatedAt,
  });

  static FavoriteModel fromMap(Json data) {
    return FavoriteModel(
      id: data['id'],
      activity: ActivityModel.fromMap(data['activity']),
      createdAt: data['created_at'],
      updatedAt: data['updated_at'],
    );
  }

  static List<FavoriteModel> fromList(List<dynamic> list) {
    return list.map((dynamic item) => FavoriteModel.fromMap(item)).toList();
  }
}
