// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class FcmTokenModel extends Equatable {
  final int id;
  final String fcmToken;
  final String createdAt;
  final String updatedAt;

  @override
  List<Object> get props => <Object>[
    id,
    fcmToken,
    createdAt,
    updatedAt,
  ];

  const FcmTokenModel({
    required this.id,
    required this.fcmToken,
    required this.createdAt,
    required this.updatedAt,
  });

  static FcmTokenModel fromMap(Json data) {
    return FcmTokenModel(
      id: data['id'],
      fcmToken: data['fcm_token'],
      createdAt: data['created_at'],
      updatedAt: data['updated_at'],
    );
  }

  static List<FcmTokenModel> fromList(List<dynamic> list) {
    return list.map((dynamic item) => FcmTokenModel.fromMap(item)).toList();
  }
}
