// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';

class GoogleUrlModel extends Equatable {
  final String url;

  @override
  List<Object> get props => <Object>[url];

  const GoogleUrlModel({required this.url});

  static GoogleUrlModel fromMap(Json data) {
    return GoogleUrlModel(url: data['url']);
  }
}
