// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';

class HealthModel extends Equatable {
  final String status;
  final String version;
  final String timestamp;

  @override
  List<Object> get props => <Object>[
    status,
    version,
    timestamp,
  ];

  const HealthModel({
    required this.status,
    required this.version,
    required this.timestamp,
  });

  static HealthModel fromMap(Json data) {
    return HealthModel(
      status: data['status'],
      version: data['version'],
      timestamp: data['timestamp'],
    );
  }

  static List<HealthModel> fromList(List<dynamic> list) {
    return list.map((dynamic item) => HealthModel.fromMap(item)).toList();
  }
}
