// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';
import 'package:sdk_flutter/domain/models/activity_model.dart';

class HighlightModel extends Equatable {
  final int id;
  final ActivityModel activity;
  final int order;
  final String? createdAt;
  final String? updatedAt;

  @override
  List<Object> get props => <Object>[
    id,
    activity,
    order,
    createdAt ?? '',
    updatedAt ?? '',
  ];

  const HighlightModel({
    required this.id,
    required this.activity,
    required this.order,
    this.createdAt,
    this.updatedAt,
  });

  static HighlightModel fromMap(Json data) {
    return HighlightModel(
      id: data['id'],
      activity: ActivityModel.fromMap(data['activity']),
      order: data['order'],
      createdAt: data['created_at'],
      updatedAt: data['updated_at'],
    );
  }

  static List<HighlightModel> fromList(List<dynamic> list) {
    return list.map((dynamic item) => HighlightModel.fromMap(item)).toList();
  }
}
