// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';

class ImageModel extends Equatable {
  final int id;
  final String path;
  final String imageUrl;

  @override
  List<Object> get props => <Object>[
    id,
    path,
    imageUrl,
  ];

  const ImageModel({
    required this.id,
    required this.path,
    required this.imageUrl,
  });

  static ImageModel fromMap(Json data) {
    return ImageModel(
      id: data['id'],
      path: data['path'],
      imageUrl: data['image_url'],
    );
  }

  static List<ImageModel> fromList(List<dynamic> list) {
    return list.map((dynamic item) => ImageModel.fromMap(item)).toList();
  }
}
