// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';

class LegalContentModel extends Equatable {
  final int id;
  final String type;
  final String description;
  final String descriptionHtml;
  final String createdAt;
  final String updatedAt;

  @override
  List<Object> get props => <Object>[
    id,
    type,
    description,
    descriptionHtml,
    createdAt,
    updatedAt,
  ];

  const LegalContentModel({
    required this.id,
    required this.type,
    required this.description,
    required this.descriptionHtml,
    required this.createdAt,
    required this.updatedAt,
  });

  static LegalContentModel fromMap(Json data) {
    return LegalContentModel(
      id: data['id'],
      type: data['type'],
      description: data['description'],
      descriptionHtml: data['description_html'],
      createdAt: data['created_at'],
      updatedAt: data['updated_at'],
    );
  }

  static List<LegalContentModel> fromList(List<dynamic> list) {
    return list.map((dynamic item) => LegalContentModel.fromMap(item)).toList();
  }
}
