// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';


class PlanModel extends Equatable {
  final int id;
  final String name;
  final String shortDescription;
  final String longDescription;
  final String frequency;
  final int value;
  final int couponLimit;
  final String createdAt;
  final String updatedAt;

  @override
  List<Object> get props => <Object>[
    id,
    name,
    shortDescription,
    longDescription,
    frequency,
    value,
    couponLimit,
    createdAt,
    updatedAt,
  ];

  const PlanModel({
    required this.id,
    required this.name,
    required this.shortDescription,
    required this.longDescription,
    required this.frequency,
    required this.value,
    required this.couponLimit,
    required this.createdAt,
    required this.updatedAt,
  });

  static PlanModel fromMap(Json data) {
    return PlanModel(
      id: data['id'],
      name: data['name'],
      shortDescription: data['short_description'],
      longDescription: data['long_description'],
      frequency: data['frequency'],
      value: data['value'],
      couponLimit: data['coupon_limit'],
      createdAt: data['created_at'],
      updatedAt: data['updated_at'],
    );
  }
}
