// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';
import 'package:sdk_flutter/domain/models/user_model.dart';
import 'package:sdk_flutter/domain/models/activity_model.dart';

class ReviewModel extends Equatable {
  final int id;
  final UserModel user;
  final ActivityModel activity;
  final String description;
  final double stars;
  final bool isVerified;
  final String createdAt;
  final String updatedAt;

  @override
  List<Object> get props => <Object>[
    id,
    user,
    activity,
    description,
    stars,
    isVerified,
    createdAt,
    updatedAt,
  ];

  const ReviewModel({
    required this.id,
    required this.user,
    required this.activity,
    required this.description,
    required this.stars,
    required this.isVerified,
    required this.createdAt,
    required this.updatedAt,
  });

  static ReviewModel fromMap(Json data) {
    return ReviewModel(
      id: data['id'],
      user: UserModel.fromMap(data['user']),
      activity: ActivityModel.fromMap(data['activity']),
      description: data['description'],
      // TODO: move it to a helper function/extension
      stars: data['stars'] is int ? data['stars'].toDouble() : data['stars'],
      isVerified: data['is_verified'],
      createdAt: data['created_at'],
      updatedAt: data['updated_at'],
    );
  }

  static List<ReviewModel> fromList(List<dynamic> list) {
    return list.map((dynamic item) => ReviewModel.fromMap(item)).toList();
  }
}
