// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';
import 'package:sdk_flutter/domain/models/plan_model.dart';

class SubscriptionModel extends Equatable {
  final int id;
  final PlanModel plan;
  final String status;
  final String createdAt;
  final String updatedAt;

  @override
  List<Object> get props => <Object>[
    id,
    plan,
    status,
    createdAt,
    updatedAt,
  ];

  const SubscriptionModel({
    required this.id,
    required this.plan,
    required this.status,
    required this.createdAt,
    required this.updatedAt,
  });

  static SubscriptionModel fromMap(Json data) {
    return SubscriptionModel(
      id: data['id'],
      plan: data['plan'],
      status: data['status'],
      createdAt: data['created_at'],
      updatedAt: data['updated_at'],
    );
  }
}
