// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class TemporaryTokenModel extends Equatable {
  final String token;
  final String expiresAt;

  @override
  List<Object> get props => <Object>[
    token,
    expiresAt,
  ];

  const TemporaryTokenModel({
    required this.token,
    required this.expiresAt,
  });

  static TemporaryTokenModel fromMap(Json data) {
    return TemporaryTokenModel(
      token: data['token'],
      expiresAt: data['expires_at'],
    );
  }

  static List<TemporaryTokenModel> fromList(List<dynamic> list) {
    return list.map((dynamic item) => TemporaryTokenModel.fromMap(item)).toList();
  }
}
