// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';


class TypeModel extends Equatable {
  final String name;
  final String nameHumanReadable;
  final String nameHumanReadablePlural;
  final String imageUrl;

  @override
  List<Object> get props => <Object>[
    name,
    nameHumanReadable,
    nameHumanReadablePlural,
    imageUrl,
  ];

  const TypeModel({
    required this.name,
    required this.nameHumanReadable,
    required this.nameHumanReadablePlural,
    required this.imageUrl,
  });

  static TypeModel fromMap(Json data) {
    return TypeModel(
      name: data['name'],
      nameHumanReadable: data['name_human_readable'],
      nameHumanReadablePlural: data['name_human_readable_plural'],
      imageUrl: data['image_url'],
    );
  }

  static List<TypeModel> fromList(List<dynamic> list) {
    return list.map((dynamic item) => TypeModel.fromMap(item)).toList();
  }
}
