// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';
import 'package:sdk_flutter/domain/models/subscription_model.dart';
import 'package:sdk_flutter/domain/models/address_model.dart';

class UserModel extends Equatable {
  final int id;
  final String name;
  final String email;
  final String? phone;
  final String? birth;
  final SubscriptionModel? subscription;
  final List<AddressModel> addresses;
  final String createdAt;
  final String updatedAt;
  final String? authorization;

  @override
  List<Object> get props => <Object>[
    id,
    name,
    email,
    phone ?? '',
    birth ?? '',
    subscription ?? {},
    addresses,
    createdAt,
    updatedAt,
    authorization ?? '',
  ];

  const UserModel({
    required this.id,
    required this.name,
    required this.email,
    this.phone,
    this.birth,
    this.subscription,
    required this.addresses,
    required this.createdAt,
    required this.updatedAt,
    this.authorization,
  });

  static UserModel fromMap(Json data) {
    return UserModel(
      id: data['id'],
      name: data['name'],
      email: data['email'],
      phone: data['phone'],
      birth: data['birth'],
      subscription: data['subscription'] != null ? SubscriptionModel.fromMap(data['subscription']) : null,
      addresses: AddressModel.fromList(data['addresses'] ?? []),
      createdAt: data['created_at'],
      updatedAt: data['updated_at'],
      authorization: data['authorization'],
    );
  }

  static List<UserModel> fromList(List<dynamic> list) {
    return list.map((dynamic item) => UserModel.fromMap(item)).toList();
  }
}
