// This file is auto generated. DO NOT edit this file manually!
import 'package:sdk_flutter/sdk_flutter.dart';

class FavoritesRepository {
  final HttpClientContract _httpClient;

  FavoritesRepository(
    this._httpClient,
  );
  
  FutureEither<bool> removeFavorite({
    required RemoveFavoriteUrlParam urlParams,
  }) async {
    Either<bool> response = await _httpClient.delete(
      url: 'api/favorites/{activity_id}',
      urlParams: urlParams.toMap(),
    );

    return response.isRight
      ? Right<bool>(response.right!)
      : Left<bool>(response.left!);
  }
  
  FutureEither<PaginatedData<FavoriteModel>> listFavorites() async {
    Either<PaginatedData<dynamic>> response = await _httpClient.index(
      url: 'api/favorites',
    );

    return response.isRight
      ? Right<PaginatedData<FavoriteModel>>(PaginatedData<FavoriteModel>(
        data: FavoriteModel.fromList(response.right!.data),
        meta: response.right!.meta,
      ))
      : Left<PaginatedData<FavoriteModel>>(response.left!);
  }
  
  FutureEither<FavoriteModel> addFavorite({
    required AddFavoriteBodyParam params,
  }) async {
    Either<Json> response = await _httpClient.post(
      url: 'api/favorites',
      data: params.toMap(),
    );

    return response.isRight
      ? Right<FavoriteModel>(FavoriteModel.fromMap(response.right!))
      : Left<FavoriteModel>(response.left!);
  }
  
}
