// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';

class PostFavoriteParam extends Equatable {
  final String activityId;

  @override
  List<Object> get props => <Object>[
    activityId,
  ];

  const PostFavoriteParam({
    required this.activityId,
  });

  Json toMap() {
    return <String, dynamic>{
      'activity_id': activityId,
    };
  }

  PostFavoriteParam copyWith({
    String? activityId,
  }) {
    return PostFavoriteParam(
      activityId: activityId ?? this.activityId,
    );
  }
}
