// This file is auto generated. DO NOT edit this file manually!
import 'package:sdk_flutter/sdk_flutter.dart';

class CouponsRepository {
  final HttpClientContract _httpClient;

  CouponsRepository(
    this._httpClient,
  );
  
  FutureEither<bool> removeCoupon({
    required RemoveCouponUrlParam urlParams,
  }) async {
    Either<bool> response = await _httpClient.delete(
      url: 'api/coupons/{coupon_id}',
      urlParams: urlParams.toMap(),
    );

    return response.isRight
      ? Right<bool>(response.right!)
      : Left<bool>(response.left!);
  }
  
  FutureEither<CouponModel> findCoupon({
    required FindCouponUrlParam urlParams,
  }) async {
    Either<Json> response = await _httpClient.get(
      url: 'api/coupons/{coupon_id}',
      urlParams: urlParams.toMap(),
    );

    return response.isRight
      ? Right<CouponModel>(CouponModel.fromMap(response.right!))
      : Left<CouponModel>(response.left!);
  }
  
  FutureEither<PaginatedData<CouponModel>> listCoupons({
    required ListCouponsQueryParam queryParams,
  }) async {
    Either<PaginatedData<dynamic>> response = await _httpClient.index(
      url: 'api/coupons',
      queryParams: queryParams.toMap(),
    );

    return response.isRight
      ? Right<PaginatedData<CouponModel>>(PaginatedData<CouponModel>(
        data: CouponModel.fromList(response.right!.data),
        meta: response.right!.meta,
      ))
      : Left<PaginatedData<CouponModel>>(response.left!);
  }
  
  FutureEither<CouponModel> addCoupon({
    required AddCouponBodyParam params,
  }) async {
    Either<Json> response = await _httpClient.post(
      url: 'api/coupons',
      data: params.toMap(),
    );

    return response.isRight
      ? Right<CouponModel>(CouponModel.fromMap(response.right!))
      : Left<CouponModel>(response.left!);
  }
  
  FutureEither<bool> editCoupon({
    required EditCouponBodyParam params,
    required EditCouponUrlParam urlParams,
  }) async {
    Either<bool> response = await _httpClient.put(
      url: 'api/coupons/{coupon_id}',
      data: params.toMap(),
      urlParams: urlParams.toMap(),
    );

    return response.isRight
      ? Right<bool>(response.right!)
      : Left<bool>(response.left!);
  }
  
}
