// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class EditCouponUrlParam extends Equatable {
  final int couponId;

  @override
  List<Object> get props => <Object>[
    couponId,
  ];

  const EditCouponUrlParam({
    required this.couponId,
  });

  Json toMap() {
    return <String, dynamic>{
      'coupon_id': couponId,
    };
  }

  EditCouponUrlParam copyWith({
    int? couponId,
  }) {
    return EditCouponUrlParam(
      couponId: couponId ?? this.couponId,
    );
  }
}
