// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class EditCouponBodyParam extends Equatable {
  final String code;
  final String type;
  final double value;
  final String activityId;
  final String? subscriptionId;

  @override
  List<Object> get props => <Object>[
    code,
    type,
    value,
    activityId,
    subscriptionId ?? '',
  ];

  const EditCouponBodyParam({
    required this.code,
    required this.type,
    required this.value,
    required this.activityId,
    this.subscriptionId,
  });

  Json toMap() {
    return <String, dynamic>{
      'code': code,
      'type': type,
      'value': value,
      'activity_id': activityId,
      'subscription_id': subscriptionId,
    };
  }

  EditCouponBodyParam copyWith({
    String? code,
    String? type,
    double? value,
    String? activityId,
    String? subscriptionId,
  }) {
    return EditCouponBodyParam(
      code: code ?? this.code,
      type: type ?? this.type,
      value: value ?? this.value,
      activityId: activityId ?? this.activityId,
      subscriptionId: subscriptionId ?? this.subscriptionId,
    );
  }
}
