// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class FindCouponUrlParam extends Equatable {
  final int couponId;

  @override
  List<Object> get props => <Object>[
    couponId,
  ];

  const FindCouponUrlParam({
    required this.couponId,
  });

  Json toMap() {
    return <String, dynamic>{
      'coupon_id': couponId,
    };
  }

  FindCouponUrlParam copyWith({
    int? couponId,
  }) {
    return FindCouponUrlParam(
      couponId: couponId ?? this.couponId,
    );
  }
}
