// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';

class IndexCouponsParam extends Equatable {
  final String? code;
  final String? type;
  final String? activityId;

  @override
  List<Object> get props => <Object>[
    code ?? '',
    type ?? '',
    activityId ?? '',
  ];

  const IndexCouponsParam({
    this.code,
    this.type,
    this.activityId,
  });

  Json toMap() {
    return <String, dynamic>{
      'code': code,
      'type': type,
      'activity_id': activityId,
    };
  }

  IndexCouponsParam copyWith({
    String? code,
    String? type,
    String? activityId,
  }) {
    return IndexCouponsParam(
      code: code ?? this.code,
      type: type ?? this.type,
      activityId: activityId ?? this.activityId,
    );
  }
}
