// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class ListCouponsQueryParam extends Equatable {
  final int? page;
  final int? perPage;
  final String? code;
  final String? type;
  final String? activityId;

  @override
  List<Object> get props => <Object>[
    page ?? 0,
    perPage ?? 0,
    code ?? '',
    type ?? '',
    activityId ?? '',
  ];

  const ListCouponsQueryParam({
    this.page,
    this.perPage,
    this.code,
    this.type,
    this.activityId,
  });

  Json toMap() {
    return <String, dynamic>{
      'page': page,
      'per_page': perPage,
      'code': code,
      'type': type,
      'activity_id': activityId,
    };
  }

  ListCouponsQueryParam copyWith({
    int? page,
    int? perPage,
    String? code,
    String? type,
    String? activityId,
  }) {
    return ListCouponsQueryParam(
      page: page ?? this.page,
      perPage: perPage ?? this.perPage,
      code: code ?? this.code,
      type: type ?? this.type,
      activityId: activityId ?? this.activityId,
    );
  }
}
