// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class AddCreditCardBodyParam extends Equatable {
  final String holderCpf;
  final String paymentToken;
  final String cardMask;

  @override
  List<Object> get props => <Object>[
    holderCpf,
    paymentToken,
    cardMask,
  ];

  const AddCreditCardBodyParam({
    required this.holderCpf,
    required this.paymentToken,
    required this.cardMask,
  });

  Json toMap() {
    return <String, dynamic>{
      'holder_cpf': holderCpf,
      'payment_token': paymentToken,
      'card_mask': cardMask,
    };
  }

  AddCreditCardBodyParam copyWith({
    String? holderCpf,
    String? paymentToken,
    String? cardMask,
  }) {
    return AddCreditCardBodyParam(
      holderCpf: holderCpf ?? this.holderCpf,
      paymentToken: paymentToken ?? this.paymentToken,
      cardMask: cardMask ?? this.cardMask,
    );
  }
}
