// This file is auto generated. DO NOT edit this file manually!
import 'package:sdk_flutter/sdk_flutter.dart';

class CreditCardsRepository {
  final HttpClientContract _httpClient;

  CreditCardsRepository(
    this._httpClient,
  );
  
  FutureEither<bool> removeCreditCard({
    required RemoveCreditCardUrlParam urlParams,
  }) async {
    Either<bool> response = await _httpClient.delete(
      url: 'api/credit-cards/{credit_card_id}',
      urlParams: urlParams.toMap(),
    );

    return response.isRight
      ? Right<bool>(response.right!)
      : Left<bool>(response.left!);
  }
  
  FutureEither<CreditCardModel> findCreditCard({
    required FindCreditCardUrlParam urlParams,
  }) async {
    Either<Json> response = await _httpClient.get(
      url: 'api/credit-cards/{credit_card_id}',
      urlParams: urlParams.toMap(),
    );

    return response.isRight
      ? Right<CreditCardModel>(CreditCardModel.fromMap(response.right!))
      : Left<CreditCardModel>(response.left!);
  }
  
  FutureEither<PaginatedData<CreditCardModel>> listCreditCards() async {
    Either<PaginatedData<dynamic>> response = await _httpClient.index(
      url: 'api/credit-cards',
    );

    return response.isRight
      ? Right<PaginatedData<CreditCardModel>>(PaginatedData<CreditCardModel>(
        data: CreditCardModel.fromList(response.right!.data),
        meta: response.right!.meta,
      ))
      : Left<PaginatedData<CreditCardModel>>(response.left!);
  }
  
  FutureEither<CreditCardModel> addCreditCard({
    required AddCreditCardBodyParam params,
  }) async {
    Either<Json> response = await _httpClient.post(
      url: 'api/credit-cards',
      data: params.toMap(),
    );

    return response.isRight
      ? Right<CreditCardModel>(CreditCardModel.fromMap(response.right!))
      : Left<CreditCardModel>(response.left!);
  }
  
}
