// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class RemoveCreditCardUrlParam extends Equatable {
  final int creditCardId;

  @override
  List<Object> get props => <Object>[
    creditCardId,
  ];

  const RemoveCreditCardUrlParam({
    required this.creditCardId,
  });

  Json toMap() {
    return <String, dynamic>{
      'credit_card_id': creditCardId,
    };
  }

  RemoveCreditCardUrlParam copyWith({
    int? creditCardId,
  }) {
    return RemoveCreditCardUrlParam(
      creditCardId: creditCardId ?? this.creditCardId,
    );
  }
}
