// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class EditPlanBodyParam extends Equatable {
  final String name;
  final String shortDescription;
  final String longDescription;
  final String frequency;
  final double value;
  final int couponLimit;

  @override
  List<Object> get props => <Object>[
    name,
    shortDescription,
    longDescription,
    frequency,
    value,
    couponLimit,
  ];

  const EditPlanBodyParam({
    required this.name,
    required this.shortDescription,
    required this.longDescription,
    required this.frequency,
    required this.value,
    required this.couponLimit,
  });

  Json toMap() {
    return <String, dynamic>{
      'name': name,
      'short_description': shortDescription,
      'long_description': longDescription,
      'frequency': frequency,
      'value': value,
      'coupon_limit': couponLimit,
    };
  }

  EditPlanBodyParam copyWith({
    String? name,
    String? shortDescription,
    String? longDescription,
    String? frequency,
    double? value,
    int? couponLimit,
  }) {
    return EditPlanBodyParam(
      name: name ?? this.name,
      shortDescription: shortDescription ?? this.shortDescription,
      longDescription: longDescription ?? this.longDescription,
      frequency: frequency ?? this.frequency,
      value: value ?? this.value,
      couponLimit: couponLimit ?? this.couponLimit,
    );
  }
}
