// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class FindPlanUrlParam extends Equatable {
  final int planId;

  @override
  List<Object> get props => <Object>[
    planId,
  ];

  const FindPlanUrlParam({
    required this.planId,
  });

  Json toMap() {
    return <String, dynamic>{
      'plan_id': planId,
    };
  }

  FindPlanUrlParam copyWith({
    int? planId,
  }) {
    return FindPlanUrlParam(
      planId: planId ?? this.planId,
    );
  }
}
