name: sdk_flutter
description: "Guiar.me - SDK Flutter"

publish_to: 'none'
version: 0.0.1

homepage: https://guiar.me

environment:
  sdk: 3.7.2
  flutter: 3.29.2

dependencies:
  flutter:
    sdk: flutter
  intl: 0.19.0

dev_dependencies:
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
    