name: sdk_flutter
description: "Guiar.me - SDK Flutter"

publish_to: 'none'
version: 1.3.6

homepage: https://guiar.me

environment:
  sdk: 3.7.2
  flutter: 3.29.2

dependencies:
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_messaging: ^15.2.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^19.2.1
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  go_router: ^15.1.3
  intl: 0.19.0
  mobx: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: 2.7.1
  path: ^1.9.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env.test
