// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class AddHighlightBodyParam extends Equatable {
  final int activityId;
  final int order;

  @override
  List<Object> get props => <Object>[
    activityId,
    order,
  ];

  const AddHighlightBodyParam({
    required this.activityId,
    required this.order,
  });

  Json toMap() {
    return <String, dynamic>{
      'activity_id': activityId,
      'order': order,
    };
  }

  AddHighlightBodyParam copyWith({
    int? activityId,
    int? order,
  }) {
    return AddHighlightBodyParam(
      activityId: activityId ?? this.activityId,
      order: order ?? this.order,
    );
  }
}
