// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class FindHighlightUrlParam extends Equatable {
  final int highlightId;

  @override
  List<Object> get props => <Object>[
    highlightId,
  ];

  const FindHighlightUrlParam({
    required this.highlightId,
  });

  Json toMap() {
    return <String, dynamic>{
      'highlight_id': highlightId,
    };
  }

  FindHighlightUrlParam copyWith({
    int? highlightId,
  }) {
    return FindHighlightUrlParam(
      highlightId: highlightId ?? this.highlightId,
    );
  }
}
