// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class AddSubscriptionBodyParam extends Equatable {
  final int planId;
  final int creditCardId;

  @override
  List<Object> get props => <Object>[
    planId,
    creditCardId,
  ];

  const AddSubscriptionBodyParam({
    required this.planId,
    required this.creditCardId,
  });

  Json toMap() {
    return <String, dynamic>{
      'plan_id': planId,
      'credit_card_id': creditCardId,
    };
  }

  AddSubscriptionBodyParam copyWith({
    int? planId,
    int? creditCardId,
  }) {
    return AddSubscriptionBodyParam(
      planId: planId ?? this.planId,
      creditCardId: creditCardId ?? this.creditCardId,
    );
  }
}
