// This file is auto generated. DO NOT edit this file manually!
import 'dart:typed_data';

import 'package:dio/dio.dart';
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class AddActivityBodyParam extends Equatable {
  final String name;
  final String description;
  final String category;
  final bool isVerified;
  final double? price;
  final String? pricePrefix;
  final String? priceSuffix;
  final String addressState;
  final String addressCity;
  final String addressNeighborhood;
  final String addressAddress;
  final String? addressZipCode;
  final String? addressNumber;
  final String? addressComplement;
  final String? imageName;
  final Uint8List? imageBytes;

  @override
  List<Object> get props => <Object>[
    name,
    description,
    category,
    isVerified,
    price ?? 0.0,
    pricePrefix ?? '',
    priceSuffix ?? '',
    addressState,
    addressCity,
    addressNeighborhood,
    addressAddress,
    addressZipCode ?? '',
    addressNumber ?? '',
    addressComplement ?? '',
  ];

  const AddActivityBodyParam({
    required this.name,
    required this.description,
    required this.category,
    required this.isVerified,
    this.price,
    this.pricePrefix,
    this.priceSuffix,
    required this.addressState,
    required this.addressCity,
    required this.addressNeighborhood,
    required this.addressAddress,
    this.addressZipCode,
    this.addressNumber,
    this.addressComplement,
    this.imageName,
    this.imageBytes,
  });

  Json toMap() {
    return <String, dynamic>{
      'name': name,
      'description': description,
      'category': category,
      'is_verified': isVerified,
      'price': price,
      'price_prefix': pricePrefix,
      'price_suffix': priceSuffix,
      'address': {
        'state': addressState,
        'city': addressCity,
        'neighborhood': addressNeighborhood,
        'address': addressAddress,
        'zip_code': addressZipCode,
        'number': addressNumber,
        'complement': addressComplement,
      },
      'image': imageBytes != null ? MultipartFile.fromBytes(imageBytes!, filename: imageName) : null,
    };
  }

  AddActivityBodyParam copyWith({
    String? name,
    String? description,
    String? category,
    bool? isVerified,
    double? price,
    String? pricePrefix,
    String? priceSuffix,
    String? addressState,
    String? addressCity,
    String? addressNeighborhood,
    String? addressAddress,
    String? addressZipCode,
    String? addressNumber,
    String? addressComplement,
    String? imageName,
    Uint8List? imageBytes,
  }) {
    return AddActivityBodyParam(
      name: name ?? this.name,
      description: description ?? this.description,
      category: category ?? this.category,
      isVerified: isVerified ?? this.isVerified,
      price: price ?? this.price,
      pricePrefix: pricePrefix ?? this.pricePrefix,
      priceSuffix: priceSuffix ?? this.priceSuffix,
      addressState: addressState ?? this.addressState,
      addressCity: addressCity ?? this.addressCity,
      addressNeighborhood: addressNeighborhood ?? this.addressNeighborhood,
      addressAddress: addressAddress ?? this.addressAddress,
      addressZipCode: addressZipCode ?? this.addressZipCode,
      addressNumber: addressNumber ?? this.addressNumber,
      addressComplement: addressComplement ?? this.addressComplement,
      imageName: imageName ?? this.imageName,
      imageBytes: imageBytes ?? this.imageBytes,
    );
  }
}
