// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';

class IndexActivitiesParam extends Equatable {
  final String? name;
  final String? category;
  final List<String>? categories;
  final String? city;

  @override
  List<Object> get props => <Object>[
    name ?? '',
    category ?? '',
    categories ?? [],
    city ?? '',
  ];

  const IndexActivitiesParam({
    this.name,
    this.category,
    this.categories,
    this.city,
  });

  Json toMap() {
    return <String, dynamic>{
      'name': name,
      'category': category,
      'categories': categories,
      'city': city,
    };
  }

  IndexActivitiesParam copyWith({
    String? name,
    String? category,
    List<String>? categories,
    String? city,
  }) {
    return IndexActivitiesParam(
      name: name ?? this.name,
      category: category ?? this.category,
      categories: categories ?? this.categories,
      city: city ?? this.city,
    );
  }
}
