// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class ListActivitiesQueryParam extends Equatable {
  final int? page;
  final int? perPage;
  final String? name;
  final String? category;
  final List<String>? categories;
  final String? city;

  @override
  List<Object> get props => <Object>[
    page ?? 0,
    perPage ?? 0,
    name ?? '',
    category ?? '',
    categories ?? [],
    city ?? '',
  ];

  const ListActivitiesQueryParam({
    this.page,
    this.perPage,
    this.name,
    this.category,
    this.categories,
    this.city,
  });

  Json toMap() {
    return <String, dynamic>{
      'page': page,
      'per_page': perPage,
      'name': name,
      'category': category,
      'categories': categories,
      'city': city,
    };
  }

  ListActivitiesQueryParam copyWith({
    int? page,
    int? perPage,
    String? name,
    String? category,
    List<String>? categories,
    String? city,
  }) {
    return ListActivitiesQueryParam(
      page: page ?? this.page,
      perPage: perPage ?? this.perPage,
      name: name ?? this.name,
      category: category ?? this.category,
      categories: categories ?? this.categories,
      city: city ?? this.city,
    );
  }
}
