include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    always_use_package_imports: true

    eol_at_end_of_file: true

    prefer_single_quotes: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_contains: true

    require_trailing_commas: true

    sort_pub_dependencies: true

    unnecessary_await_in_return: true
    unnecessary_breaks: true
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_final: true
    unnecessary_late: true
    unnecessary_new: true
    unnecessary_parenthesis: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unnecessary_to_list_in_spreads: true

    use_super_parameters: true
