name: ui_flutter
description: "Guiar.me - UI Flutter"

publish_to: 'none'
version: 1.0.4

homepage: https://guiar.me

environment:
  sdk: 3.7.2
  flutter: 3.29.2

dependencies:
  flutter:
    sdk: flutter
  flutter_quill: ^11.4.0
  flutter_svg: ^2.1.0
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  intl: 0.19.0
  vsc_quill_delta_to_html: ^1.0.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
