// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class AddFcmTokenBodyParam extends Equatable {
  final String fcmToken;

  @override
  List<Object> get props => <Object>[
    fcmToken,
  ];

  const AddFcmTokenBodyParam({
    required this.fcmToken,
  });

  Json toMap() {
    return <String, dynamic>{
      'fcm_token': fcmToken,
    };
  }

  AddFcmTokenBodyParam copyWith({
    String? fcmToken,
  }) {
    return AddFcmTokenBodyParam(
      fcmToken: fcmToken ?? this.fcmToken,
    );
  }
}
