// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class EditUserUrlParam extends Equatable {
  final int userId;

  @override
  List<Object> get props => <Object>[
    userId,
  ];

  const EditUserUrlParam({
    required this.userId,
  });

  Json toMap() {
    return <String, dynamic>{
      'user_id': userId,
    };
  }

  EditUserUrlParam copyWith({
    int? userId,
  }) {
    return EditUserUrlParam(
      userId: userId ?? this.userId,
    );
  }
}
