// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';

class GetGoogleCallbackParam extends Equatable {
  final String code;

  @override
  List<Object> get props => <Object>[
    code,
  ];

  const GetGoogleCallbackParam({
    required this.code,
  });

  Json toMap() {
    return <String, dynamic>{
      'code': code,
    };
  }

  GetGoogleCallbackParam copyWith({
    String? code,
  }) {
    return GetGoogleCallbackParam(
      code: code ?? this.code,
    );
  }
}
