// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';

class PostFcmTokenParam extends Equatable {
  final String fcmToken;

  @override
  List<Object> get props => <Object>[
    fcmToken,
  ];

  const PostFcmTokenParam({
    required this.fcmToken,
  });

  Json toMap() {
    return <String, dynamic>{
      'fcm_token': fcmToken,
    };
  }

  PostFcmTokenParam copyWith({
    String? fcmToken,
  }) {
    return PostFcmTokenParam(
      fcmToken: fcmToken ?? this.fcmToken,
    );
  }
}
