// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';

class PutUserParam extends Equatable {
  final String name;
  final String email;
  final String phone;
  final String birth;
  final int? addressId;
  final String addressState;
  final String addressCity;
  final String addressNeighborhood;
  final String addressAddress;
  final String? addressZipCode;
  final String? addressNumber;
  final String? addressComplement;

  @override
  List<Object> get props => <Object>[
    name,
    email,
    phone,
    birth,
    addressId ?? 0,
    addressState,
    addressCity,
    addressNeighborhood,
    addressAddress,
    addressZipCode ?? '',
    addressNumber ?? '',
    addressComplement ?? '',
  ];

  const PutUserParam({
    required this.name,
    required this.email,
    required this.phone,
    required this.birth,
    this.addressId,
    required this.addressState,
    required this.addressCity,
    required this.addressNeighborhood,
    required this.addressAddress,
    this.addressZipCode,
    this.addressNumber,
    this.addressComplement,
  });

  Json toMap() {
    return <String, dynamic>{
      'name': name,
      'email': email,
      'phone': phone,
      'birth': birth,
      'address': {
        'id': addressId,
        'state': addressState,
        'city': addressCity,
        'neighborhood': addressNeighborhood,
        'address': addressAddress,
        'zip_code': addressZipCode,
        'number': addressNumber,
        'complement': addressComplement
      },
    };
  }

  PutUserParam copyWith({
    String? name,
    String? email,
    String? phone,
    String? birth,
    int? addressId,
    String? addressState,
    String? addressCity,
    String? addressNeighborhood,
    String? addressAddress,
    String? addressZipCode,
    String? addressNumber,
    String? addressComplement,
  }) {
    return PutUserParam(
      name: name ?? this.name,
      email: email ?? this.email,
      phone: phone ?? this.phone,
      birth: birth ?? this.birth,
      addressId: addressId ?? this.addressId,
      addressState: addressState ?? this.addressState,
      addressCity: addressCity ?? this.addressCity,
      addressNeighborhood: addressNeighborhood ?? this.addressNeighborhood,
      addressAddress: addressAddress ?? this.addressAddress,
      addressZipCode: addressZipCode ?? this.addressZipCode,
      addressNumber: addressNumber ?? this.addressNumber,
      addressComplement: addressComplement ?? this.addressComplement,
    );
  }
}
