// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';

class SignInUserParam extends Equatable {
  final String password;
  final String email;

  @override
  List<Object> get props => <Object>[
    password,
    email,
  ];

  const SignInUserParam({
    required this.password,
    required this.email,
  });

  Json toMap() {
    return <String, dynamic>{
      'password': password,
      'email': email,
    };
  }

  SignInUserParam copyWith({
    String? password,
    String? email,
  }) {
    return SignInUserParam(
      password: password ?? this.password,
      email: email ?? this.email,
    );
  }
}
