// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/core/types/json.dart';

class SignUpUserParam extends Equatable {
  final String name;
  final String email;
  final String password;

  @override
  List<Object> get props => <Object>[
    name,
    email,
    password,
  ];

  const SignUpUserParam({
    required this.name,
    required this.email,
    required this.password,
  });

  Json toMap() {
    return <String, dynamic>{
      'name': name,
      'email': email,
      'password': password,
    };
  }

  SignUpUserParam copyWith({
    String? name,
    String? email,
    String? password,
  }) {
    return SignUpUserParam(
      name: name ?? this.name,
      email: email ?? this.email,
      password: password ?? this.password,
    );
  }
}
