name: Release

on:
  push:
    branches:
      - main
    paths:
      - '.changeset/**'
      - '.github/workflows/**'

permissions:
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Create Release Pull Request or Create Release
        uses: changesets/action@v1
        with:
          title: 'chore: update versions'
          commit: 'chore: update versions'
          publish: npx changeset publish
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
