// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class EditLegalContentUrlParam extends Equatable {
  final int type;

  @override
  List<Object> get props => <Object>[
    type,
  ];

  const EditLegalContentUrlParam({
    required this.type,
  });

  Json toMap() {
    return <String, dynamic>{
      'type': type,
    };
  }

  EditLegalContentUrlParam copyWith({
    int? type,
  }) {
    return EditLegalContentUrlParam(
      type: type ?? this.type,
    );
  }
}
