// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class EditLegalContentBodyParam extends Equatable {
  final String description;
  final String? descriptionHtml;

  @override
  List<Object> get props => <Object>[
    description,
    descriptionHtml ?? '',
  ];

  const EditLegalContentBodyParam({
    required this.description,
    this.descriptionHtml,
  });

  Json toMap() {
    return <String, dynamic>{
      'description': description,
      'description_html': descriptionHtml,
    };
  }

  EditLegalContentBodyParam copyWith({
    String? description,
    String? descriptionHtml,
  }) {
    return EditLegalContentBodyParam(
      description: description ?? this.description,
      descriptionHtml: descriptionHtml ?? this.descriptionHtml,
    );
  }
}
