// This file is auto generated. DO NOT edit this file manually!
import 'package:equatable/equatable.dart';
import 'package:sdk_flutter/sdk_flutter.dart';

class FindLegalContentUrlParam extends Equatable {
  final String type;

  @override
  List<Object> get props => <Object>[
    type,
  ];

  const FindLegalContentUrlParam({
    required this.type,
  });

  Json toMap() {
    return <String, dynamic>{
      'type': type,
    };
  }

  FindLegalContentUrlParam copyWith({
    String? type,
  }) {
    return FindLegalContentUrlParam(
      type: type ?? this.type,
    );
  }
}
