// This file is auto generated. DO NOT edit this file manually!
import 'package:sdk_flutter/sdk_flutter.dart';

class LegalContentsRepository {
  final HttpClientContract _httpClient;

  LegalContentsRepository(
    this._httpClient,
  );
  
  FutureEither<LegalContentModel> findLegalContent({
    required FindLegalContentUrlParam urlParams,
  }) async {
    Either<Json> response = await _httpClient.get(
      url: 'api/legal-contents/{type}',
      urlParams: urlParams.toMap(),
    );

    return response.isRight
      ? Right<LegalContentModel>(LegalContentModel.fromMap(response.right!))
      : Left<LegalContentModel>(response.left!);
  }
  
  FutureEither<bool> editLegalContent({
    required EditLegalContentBodyParam params,
    required EditLegalContentUrlParam urlParams,
  }) async {
    Either<bool> response = await _httpClient.put(
      url: 'api/legal-contents/{type}',
      data: params.toMap(),
      urlParams: urlParams.toMap(),
    );

    return response.isRight
      ? Right<bool>(response.right!)
      : Left<bool>(response.left!);
  }
  
}
